### ISSUE TITLE
WB TABLE?

### ISSUE THREAD

**Issue by Kumicoo** [Moorleiche/afk-hunt#10]
X

**Comment by Kumicoo** [comment]
Now wbtable is not working at all!

**Comment by Moorleiche** [comment]
Thunder = Worldboss Found by Module User

**Comment by Kumicoo** [comment]
So the thunder means that someone who uses THIS module has found a worlboss there?? But why is there a thunder when the worldboss is on cooldown? What exactly does it mean now? Excuse my stupidity.

**Comment by Moorleiche** [comment]
Just ignore the Thunder... If i find wb with module, but someone other is doing it, i just ignore this wb and thunder stay

**Comment by Chinaraku** [comment]
having an error opening wbtable,
how to fix?
