### ISSUE TITLE
channel?

### ISSUE THREAD

**Issue by q848899** [Moorleiche/afk-hunt#12]
![1111](https://user-images.githubusercontent.com/16863960/36932724-768909a4-1f08-11e8-9b7c-cd6f9191317c.png)
What is the reason for this？

**Comment by q848899** [comment]
And every time I use it
![2222](https://user-images.githubusercontent.com/16863960/36932824-30584f88-1f0a-11e8-9498-544ab01a6db3.png) 
Automatic opening autohunt

**Comment by q848899** [comment]
And every time I use it
![2222](https://user-images.githubusercontent.com/16863960/36932842-84d67ff8-1f0a-11e8-90ce-e267abaeab89.png)
Automatic opening autohunt  
I don't know why

**Comment by Shalltearz** [comment]
You can activate deactivate it via command

**Comment by Moorleiche** [comment]
@q848899 congratulation, u found the secret trigger item :D

check source code and look for TRIGGER_ITEM, u can change it

**Comment by Moorleiche** [comment]
There was a channel bug, it is already fixed right now. otherwise type !wbskip

**Comment by Shalltearz** [comment]
Lol via item thought it just work via command or both?

**Comment by Shalltearz** [comment]
Ah ok

**Comment by q848899** [comment]
I know it's a shortcut, right
Custom props
