### ISSUE TITLE
opcodes question

### ISSUE THREAD

**Issue by q848899** [Moorleiche/afk-hunt#14]
How to get the right C_TELEPORT_TO_VILLAGE？
I've been trying for a long time to be wrong
I find that I can't send the next point.

**Comment by q848899** [comment]
How to trigger the right code

**Comment by q848899** [comment]
There is a code that is responsive
But the system hints are incapable of action

**Comment by q848899** [comment]
Is it necessary for anything to be on the body

**Comment by q848899** [comment]
Can you tell me that I can't move automatically to the next point because of this reason

Or I was wrong for another reason

**Comment by Moorleiche** [comment]
Hey i can't check OP Codes for TW Servers, so u have to ask in tera-proxy discord or find out by yourself. Check This repo:
https://github.com/hackerman-caali/data-logger/tree/master/update/map
Or use Data Logger to get ur OP Codes...
I see 3-4 People who hunt on TW with this module, so it have to be possible.

**Comment by Moorleiche** [comment]
And ofc check ur Tera-Proxy Console, there u will see errors by missing OPCodes.

**Comment by q848899** [comment]
I used alex-packet-id-finder  Find a lot of mistakes code
Can tell me how to trigger the right code?

**Comment by q848899** [comment]
For example, what kind of operation can trigger this code   T T

**Comment by q848899** [comment]
I caught 8 or more error codes and went crazy

**Comment by q848899** [comment]
Then you can tell me that it's this one code decided whether you can automatically go to the next point.
My problem now is the ability to change channels automatically 
But it doesn't move to the last channel. You need to switch the channel manually to jump to the next point

**Comment by q848899** [comment]
But it needs to be in the same area
A large map that does not include a large map will fly directly to an empty place

**Comment by Moorleiche** [comment]
idk where your problem is :D 
use "logc" open village map and confirm ur teleport to any village, the following OPCode in ur tera-proxy console have to be for "C_TELEPORT_TO_VILLAGE"...
to get "S_CURRENT_CHANNEL" type "logs" and switch ur channel, immediatly after loading new channel u can catch it in ur tera-proxy console...
"C_SELECT_CHANNEL" use "logc" and trigger it while selecting new channel.

**Comment by q848899** [comment]
use logc  Prompt this
![aaaa](https://user-images.githubusercontent.com/16863960/37034180-6349868e-2183-11e8-90be-98f45d0cebca.png) but C_REQUEST_GAMESTAT_PING = 49362
but this is calli Provided
Is he wrong?
