### ISSUE TITLE
"failed to generate S_SHOW_AWESOMIUMWEB_SHOP<1>"

### ISSUE THREAD

**Issue by keyzthecheater** [Moorleiche/afk-hunt#17]
Can you help me plz ?
[https://www.noelshack.com/2018-10-4-1520543565-plzhelpme.jpg](url)

**Comment by keyzthecheater** [comment]
https://image.noelshack.com/fichiers/2018/10/4/1520543565-plzhelpme.jpg

**Comment by Moorleiche** [comment]
Join discord channel of tera-proxy and aks there for missing OPCODE
