### ISSUE TITLE
 In situ tp?

### ISSUE THREAD

**Issue by q848899** [Moorleiche/afk-hunt#18]
Can't it be tp or any other reason

**Comment by Moorleiche** [comment]
dont'k know what "sito" means, also don't understand ur description

**Comment by q848899** [comment]
Find the reason 
They are newly updated proxy There is this S_SPAWN_ME.2.def
cause Can't transport

**Comment by q848899** [comment]
I don't know I can't transport Other VILLAGE 
What is the reason It should have nothing to do with opcodes

**Comment by Moorleiche** [comment]
I understand, will fix it.

**Comment by Moorleiche** [comment]
Okay i added Version 1 of S_SPAWN_ME but can't test it by myself, i think ure right, or u have already fixed it :+1:

**Comment by q848899** [comment]
Finally I found the problem
![1111](https://user-images.githubusercontent.com/16863960/37562959-1bbb977c-2ab0-11e8-943b-2c2f90410c9c.png)The position of our props is different

 dispatch.toServer('C_PCBANGINVENTORY_USE_SLOT', 1, { slot : 2 });
So it's OK
