### ISSUE TITLE
Still not working?

### ISSUE THREAD

**Issue by Kumicoo** [Moorleiche/afk-hunt#2]
sorry if im a bit retarded. Does it only hunt 68's ? Or every level worldboss? 

Very very nice module. Would love to tax 1 emerald each time, because this is really great. Thanks!

**Comment by Moorleiche** [comment]
ty mate, just leave me a star :)
yeah it have some bugs atm but i will try to fix asap

**Comment by Kumicoo** [comment]
Nice! Please notify me of any fixes or changes :)
