### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by mascoxeig** [Moorleiche/afk-hunt#23]
This is regarding the wbtable, I cannot seem to find any way of contacting you about it. I see that both the 
webinterface and the table are limited access. If there is something I have to do to get access, I would 
like to know. Please let me know. My email is jets22@protonmail.com.

**Comment by Moorleiche** [comment]
moorleiche#0601 @discord

**Comment by mascoxeig** [comment]
I have added you under the name Markz
