### ISSUE TITLE
Script needs update to run

### ISSUE THREAD

**Issue by Moorleiche** [Moorleiche/afk-hunt#25]
just copy/paste index.js

**Comment by q848899** [comment]
Many mistakes are made 
Unable to upload pictures
it like S_SYSTEM_MESSAGE
A mistake like @2833  @346 
But it does not affect the use of
I don't know why

**Comment by q848899** [comment]
![333](https://user-images.githubusercontent.com/16863960/38027491-69939f2a-32c2-11e8-890a-c0d5b73f1b58.png)

**Comment by Moorleiche** [comment]
ty for info, this error is made by the database server. sysmsg was not defined but is fixed yet... pls check again :)

**Comment by q848899** [comment]
It's all right. :)
