### ISSUE TITLE
Wbtable dont work

### ISSUE THREAD

**Issue by Vasy86le** [Moorleiche/afk-hunt#26]
Hi, when it type wbtable, nothing happen in game but i get error in proxy console, what to do to can use wbtable?

**Comment by q848899** [comment]
Do you have S_SHOW_AWESOMIUMWEB_SHOP？

**Comment by Vasy86le** [comment]
I dont know, but i saw this S_SHOW_AWESOMIUMWEB_SHOP In error, 
From where to get this file?

**Comment by q848899** [comment]
inspect tera-proxy\node_modules\tera-data\protocol\S_SHOW_AWESOMIUMWEB_SHOP.1.def
If there is You are missing opcode

**Comment by mattuk1** [comment]
same I inspect and ther it says string line

**Comment by q848899** [comment]
You check opcode？

**Comment by mattuk1** [comment]
i think i did but im not sure what do i have to find or how

**Comment by q848899** [comment]
https://github.com/beng-mods/opcodes-4-dummies
Look at this.

**Comment by mattuk1** [comment]
yup I think i done all and protcols maps and opcodes are there
wbtable

**Comment by q848899** [comment]
I did it.
I can see it

**Comment by mattuk1** [comment]
t-t

**Comment by q848899** [comment]
You can be sure S_SHOW_AWESOMIUMWEB_SHOP Is it right?

**Comment by mattuk1** [comment]
so i did all then i do

logs

fpi S_showawesomeiumweb_shop

and then?

**Comment by q848899** [comment]
Do this at the same time
Open the shop in the game
The correct opcodes will be captured at this time

**Comment by mattuk1** [comment]
damn

**Comment by mattuk1** [comment]
i open the region map then i input
S_SHOWAWESOMEUIMWEB_SHOP = (WICH NUMBERS THERE?)*

**Comment by q848899** [comment]
like this
![111](https://user-images.githubusercontent.com/16863960/38173816-80972eda-35f6-11e8-85fc-7158f180ccf6.png)

**Comment by mattuk1** [comment]
nothing changes, ive erased and installed all again 

i have a problem option.uri with Request master can be that the problem?

**Comment by Vasy86le** [comment]
Thx for help, was op code, now work fine.

**Comment by q848899** [comment]
Request master Under this directory \tera-proxy\node_modules

**Comment by mattuk1** [comment]
done and still getting the same error while request table
also i get some errors while doing "npm install request" at tera-proxy/node-modules

**Comment by Moorleiche** [comment]
don't run "npm install" in tera-proxy/node_modules/ ... run it in tera-proxy/ also update newest version of node.js plx

**Comment by mattuk1** [comment]
ok let me see i ve done all now i dont see any error but when i 

/proxy wbtable 
there no rply and nothing pop in console now

it does pop when i do wbhunt 

comand or somehting like that it works 

but wbtable 
not
