### ISSUE TITLE
Channel: ?

### ISSUE THREAD

**Issue by Zawiz** [Moorleiche/afk-hunt#27]
Check Next: Nyxarras, Checkpoint: 1, Channel: ?

Switching Boss...
1, 2, 3 Open
3 Checked
Check Next: Betsael, Checkpoint: 1, Channel: ?
Response: Check submitted!

**Comment by q848899** [comment]
It's normal
It should be checked  next point Has anyone hit boss
If someone has done it It will skip

**Comment by Moorleiche** [comment]
? = Doomzone
