### ISSUE TITLE
can't get module to work at all?

### ISSUE THREAD

**Issue by seiiun** [Moorleiche/afk-hunt#28]
i downloaded both command and request modules but both afkhunt and request show that a file is missing

![screenshot_1](https://user-images.githubusercontent.com/37954642/38187500-df3019e6-3625-11e8-81ba-bc7b7c3e5d06.png)

**Comment by q848899** [comment]
https://github.com/justmoon/node-extend
It seems that you lack this document

**Comment by Moorleiche** [comment]
pls learn how to install modules on node.js...

#3
