### ISSUE TITLE
S_SHOW_AWESOMIUMWEB_SHOP

### ISSUE THREAD

**Issue by Divinemech** [Moorleiche/afk-hunt#29]
hey!
wbtable isnt working to me
i did input opcode at tera-proxy\node_modules\tera-data\map.
what can i do?

**Comment by Vasy86le** [comment]
logs not logc , and fpi S_SHOW_AWESOMIUMWEB_SHOP , after you write this commands, open tera store in game and watch in proxy console to take id and write that S_SHOW_AWESOMIUMWEB_SHOP = id code , in map folder, file, protocol.328428, save file and must work

**Comment by Divinemech** [comment]
got it, tyvm!
