### ISSUE TITLE
Can you upload Request zip ?

### ISSUE THREAD

**Issue by Denver3D** [Moorleiche/afk-hunt#3]
hello,

I can't get the module work, I have this error each time, and I think the probleme come from the Request file that I've downloaded

https://i.imgur.com/qw3AAbt.png

**Comment by Moorleiche** [comment]
go in tera-proxy folder -> shift + rightclick -> run cmd/powershell here -> npm install request

**Comment by Denver3D** [comment]
Work like a charm thank you, do you have discord ?

**Comment by Moorleiche** [comment]
hey mate just for private sry :P
