### ISSUE TITLE
Could you add a feature to display the potential spawn points/checkpoints on minimap

### ISSUE THREAD

**Issue by Shrubbity** [Moorleiche/afk-hunt#32]
I don't really want to use the teleport function since it seems risky as hell, especially since you're teleporting to about 3 different spawn points per boss, and the travel journal can only store 5 potential locations.

World-bam-notifier gives you a <Point of Interest> notification like so: https://github.com/teralove/world-bam-notifier/blob/master/index.js

I was wondering if you could do something like that, and a standalone autochannel feature would be cool (as long as you're in same map as BAM it changes to potential channels or something).

Cheers

**Comment by Moorleiche** [comment]
Hey, sry no features yet. Also the Mini-Map is 100% Clientside, so no Chance to Proxy-Script it.
