### ISSUE TITLE
setting up our own pos for WB, and able to skip some of them

### ISSUE THREAD

**Issue by Denver3D** [Moorleiche/afk-hunt#4]
Hello again,

I wanted to know if it's possible to edit the wbhunt pos to put our own list and if we can skip some of them manually by code, cause I've tried but it seems we can't edit POS or anything (everything server sided ?!)

**Comment by Moorleiche** [comment]
worldbosses and open channels are directly connected to the server, depends where are u hunting the modules asks server for known kills and possible spawned wbs. u can add other bosses but u cant skip them... what server are u playing? maybe i can give u access to webinterface

**Comment by Denver3D** [comment]
On seren can I provide any help for the pos ? Sometimes I got attacked by monsters on the actual pos :c ,

and for auto attacking I've found out this https://github.com/Gus-Was-Taken/Tera-PVE-Bot idk if it's working,

**Comment by Moorleiche** [comment]
what loc u get attacked?

**Comment by Denver3D** [comment]
On lyniphi some trash mobs come to attack me :(

**Comment by Denver3D** [comment]
There is really no way for us to use our own rotation of wbhunt pos ? and send our pos & wb information to the webinterface ? Like that we won't find out 100 person teleporting to the same pos, and we can manage to make it faster for research

**Comment by Moorleiche** [comment]
No u can do ur own module with ur own data and without database connection, but sharing times makes more sense, so the module can skip done worlbosses with this information. I will fix Linyphi Pos.

**Comment by Denver3D** [comment]
I see :( Unfortunately I'm good on a lot of stuff like creating forum/website or even manage vps server on linux, but I'm really usless when it's about modules :'( If I've had an exemple I can manage to make better pos and faster for wbhunt :( 

and thank you for Linyphi fix

**Comment by Moorleiche** [comment]
fixed
