### ISSUE TITLE
Nyxarras Channel

### ISSUE THREAD

**Issue by Moorleiche** [Moorleiche/afk-hunt#6]
On EU we have 10 ch now, how is about other regions?

**Comment by Denver3D** [comment]
Is it possible to add them for EU servers ? for now it only check Until Ch 4 before tp to another location :(

**Comment by Moorleiche** [comment]
disable wbskip so the server get initial data from all channel

**Comment by Moorleiche** [comment]
after that u can enable wbskip again

**Comment by Denver3D** [comment]
Disabled by default and still the same probleme :(

It check only 1,2,3,4 on nyxa instead of 10 channels

**Comment by Moorleiche** [comment]
okay, then visit each chan one time manually. it should work

**Comment by Denver3D** [comment]
Works ! <3
