### ISSUE TITLE
Play a sound when he find a wb

### ISSUE THREAD

**Issue by Denver3D** [Moorleiche/afk-hunt#8]
Hello,

I wanted to know if you can play a sound like beep.wav something like that each time he found out a wb ?

And can you add a function wbplayer to skip that wb cause it's already been doing by someone else ? :c

**Comment by Moorleiche** [comment]
this isnt a bug, this are premuim features ;) but maybe i will add a beep :D

**Comment by Moorleiche** [comment]
Sound or TextToSpeech is not worth installing additional Modules, so I wont add this Feature.
