### ISSUE TITLE
Error:cannot find module "extend"

### ISSUE THREAD

**Issue by Kakkio** [Moorleiche/afk-hunt#9]
I keep getting Failed to load for afkhunt and request.

Error:cannot find module "extend"  can you please help?

**Comment by Chewwypie** [comment]
Same problem, how to fix this? :/

**Comment by Moorleiche** [comment]
1. Go to tera-proxy main folder (where run.bat is)
2. Press SHIFT + Right Click
3. Open CMD/Powershell Window here
4. Type: npm install request

**Comment by Kakkio** [comment]
i get so many errors when trying to run it in the proxy, any idea?

**Comment by Moorleiche** [comment]
In most cases this are missing OP Codes... Just got OP Codes for EU
